package it.polimi.ingsw.communications.serveranswers;

/**
 * This class contains the server's information about the status of connection.
 */
public class ConnectionOutcome implements Answer{
    private final boolean isConnected;
    private final String answer;

    /**
     * Unique ID generated by the server.
     */
    private final Integer ID;

    /**
     * Class constructor.
     * @param bool
     * @param answer
     */
    public ConnectionOutcome(boolean isConnected, Integer ID, String answer){
        this.answer = answer;
        this.isConnected = isConnected;
        this.ID = ID;
    }

    /**
     * Answer getter.
     * @return
     */
    public Object getAnswer() {
        return answer;
    }

    /**
     * ID getter.
     * @return
     */
    public Integer getID() {
        return ID;
    }

    /**
     * Method to know if the connection was successful.
     * @return
     */
    public boolean isConnected(){
        return isConnected;
    }



}
