package it.polimi.ingsw.communications.serveranswers.info;

import it.polimi.ingsw.communications.serveranswers.Answer;

/**
 * Information message to the client about the status of connection.
 * It contains all the information to start the client properly.
 */
public class ConnectionOutcome implements Answer {
    /**
     * Status bit that represent the status of the connection.
     */
    private final boolean isConnected;
    private final String answer;

    /**
     * Unique ID generated by the server.
     */
    private final Integer ID;

    /**
     * Class constructor.
     * @param isConnected Status bit that represent the status of the connection.
     * @param answer answer from the server.
     */
    public ConnectionOutcome(boolean isConnected, Integer ID, String answer){
        this.answer = answer;
        this.isConnected = isConnected;
        this.ID = ID;
    }

    /**
     * {@inheritDoc}
     * @return answer from the server.
     */
    public Object getAnswer() {
        return answer;
    }

    /**
     * ID getter.
     * @return unique ID generated by the server.
     */
    public Integer getID() {
        return ID;
    }

    /**
     * Method to know if the connection was successful.
     * @return Status bit that represent the status of the connection.
     */
    public boolean isConnected(){
        return isConnected;
    }
}
